-- MySQL Script generated by MySQL Workbench
-- Fri Dec  1 23:53:24 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_perpustakaan
-- -----------------------------------------------------

-- -----------`anggota``db_perpustakaan`------------------------------------------
-- Schema db_perpustakaan
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_perpustakaan` DEFAULT CHARACTER SET utf8 ;
USE `db_perpustakaan` ;

-- -----------------------------------------------------
-- Table `db_perpustakaan`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_perpustakaan`.`User` (
  `ID_User` CHAR(10) NOT NULL,
  `Nama_User` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Password` CHAR(100) NOT NULL,
  `Level` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_User`))
ENGINE = INNODB;


-- -----------------------------------------------------
-- Table `db_perpustakaan`.`Anggota`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_perpustakaan`.`Anggota` (
  `ID_Anggota` CHAR(10) NOT NULL,
  `Nama_Anggota` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Telpon` VARCHAR(15) NOT NULL,
  `Tanggal_Bergabung` DATE NOT NULL,
  PRIMARY KEY (`ID_Anggota`))
ENGINE = INNODB;


-- -----------------------------------------------------
-- Table `db_perpustakaan`.`Kategori`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_perpustakaan`.`Kategori` (
  `ID_Kategori` CHAR(10) NOT NULL,
  `Nama_Kategori` VARCHAR(45) NOT NULL,
  `Deskripsi_Kategori` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_Kategori`))
ENGINE = INNODB;


-- -----------------------------------------------------
-- Table `db_perpustakaan`.`Penerbit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_perpustakaan`.`Penerbit` (
  `ID_Penerbit` CHAR(10) NOT NULL,
  `Nama_Penerbit` VARCHAR(45) NOT NULL,
  `Situs_Penerbit` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_Penerbit`))
ENGINE = INNODB;


-- -----------------------------------------------------
-- Table `db_perpustakaan`.`Buku`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_perpustakaan`.`Buku` (
  `ID_Buku` CHAR(10) NOT NULL,
  `Judul_Buku` VARCHAR(45) NOT NULL,
  `Pengarang_Buku` VARCHAR(45) NOT NULL,
  `Tahun_Terbit` VARCHAR(10) NOT NULL,
  `ID_Kategori` CHAR(10) NOT NULL,
  `ID_Penerbit` CHAR(10) NOT NULL,
  PRIMARY KEY (`ID_Buku`),
  INDEX `fk_Buku_Kategori1_idx` (`ID_Kategori` ASC) VISIBLE,
  INDEX `fk_Buku_Penerbit1_idx` (`ID_Penerbit` ASC) VISIBLE,
  CONSTRAINT `fk_Buku_Kategori1`
    FOREIGN KEY (`ID_Kategori`)
    REFERENCES `db_perpustakaan`.`Kategori` (`ID_Kategori`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Buku_Penerbit1`
    FOREIGN KEY (`ID_Penerbit`)
    REFERENCES `db_perpustakaan`.`Penerbit` (`ID_Penerbit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_perpustakaan`.`Peminjaman`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_perpustakaan`.`Peminjaman` (
  `ID_Peminjaman` CHAR(10) NOT NULL,
  `Tanggal_Peminjaman` DATE NOT NULL,
  `Tanggal_Pengembalian` DATE NOT NULL,
  `Status_Peminjaman` VARCHAR(45) NOT NULL,
  `ID_User` CHAR(10) NOT NULL,
  `ID_Anggota` CHAR(10) NOT NULL,
  PRIMARY KEY (`ID_Peminjaman`),
  INDEX `fk_Peminjaman_User_idx` (`ID_User` ASC) VISIBLE,
  INDEX `fk_Peminjaman_Anggota1_idx` (`ID_Anggota` ASC) VISIBLE,
  UNIQUE INDEX `Status_Peminjaman_UNIQUE` (`Status_Peminjaman` ASC) VISIBLE,
  UNIQUE INDEX `ID_User_UNIQUE` (`ID_User` ASC) VISIBLE,
  CONSTRAINT `fk_Peminjaman_User`
    FOREIGN KEY (`ID_User`)
    REFERENCES `db_perpustakaan`.`User` (`ID_User`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Peminjaman_Anggota1`
    FOREIGN KEY (`ID_Anggota`)
    REFERENCES `db_perpustakaan`.`Anggota` (`ID_Anggota`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_perpustakaan`.`Detail_Peminjaman`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_perpustakaan`.`Detail_Peminjaman` (
  `ID_Peminjaman` CHAR(10) NOT NULL,
  `ID_Buku` CHAR(10) NOT NULL,
  `Status_Pengembalian` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_Peminjaman`),
  INDEX `fk_Detail_Peminjaman_Buku1_idx` (`ID_Buku` ASC) VISIBLE,
  CONSTRAINT `fk_Detail_Peminjaman_Peminjaman1`
    FOREIGN KEY (`ID_Peminjaman`)
    REFERENCES `db_perpustakaan`.`Peminjaman` (`ID_Peminjaman`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Detail_Peminjaman_Buku1`
    FOREIGN KEY (`ID_Buku`)
    REFERENCES `db_perpustakaan`.`Buku` (`ID_Buku`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_perpustakaan`.`Pengembalian`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_perpustakaan`.`Pengembalian` (
  `ID_Pengembalian` CHAR(10) NOT NULL,
  `Tanggal_Pengembalian` DATE NOT NULL,
  `Denda_Pengembalian` DOUBLE NOT NULL,
  `ID_Peminjaman` CHAR(10) NOT NULL,
  `ID_Anggota` CHAR(10) NOT NULL,
  PRIMARY KEY (`ID_Pengembalian`),
  INDEX `fk_Pengembalian_Peminjaman1_idx` (`ID_Peminjaman` ASC) VISIBLE,
  INDEX `fk_Pengembalian_Anggota1_idx` (`ID_Anggota` ASC) VISIBLE,
  CONSTRAINT `fk_Pengembalian_Peminjaman1`
    FOREIGN KEY (`ID_Peminjaman`)
    REFERENCES `db_perpustakaan`.`Peminjaman` (`ID_Peminjaman`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pengembalian_Anggota1`
    FOREIGN KEY (`ID_Anggota`)
    REFERENCES `db_perpustakaan`.`Anggota` (`ID_Anggota`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_perpustakaan`.`Detail_Pengembalian`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_perpustakaan`.`Detail_Pengembalian` (
  `ID_Pengembalian` CHAR(10) NOT NULL,
  `ID_Buku` CHAR(10) NOT NULL,
  `Jumlah_Denda` DOUBLE NOT NULL,
  PRIMARY KEY (`ID_Pengembalian`, `ID_Buku`),
  INDEX `fk_Detail_Pengembalian_Buku1_idx` (`ID_Buku` ASC) VISIBLE,
  CONSTRAINT `fk_Detail_Pengembalian_Pengembalian1`
    FOREIGN KEY (`ID_Pengembalian`)
    REFERENCES `db_perpustakaan`.`Pengembalian` (`ID_Pengembalian`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Detail_Pengembalian_Buku1`
    FOREIGN KEY (`ID_Buku`)
    REFERENCES `db_perpustakaan`.`Buku` (`ID_Buku`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_perpustakaan`.`Sementara`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_perpustakaan`.`Sementara` (
  `ID_Buku` CHAR(10) NOT NULL,
  INDEX `fk_Sementara_Buku1_idx` (`ID_Buku` ASC) VISIBLE,
  CONSTRAINT `fk_Sementara_Buku1`
    FOREIGN KEY (`ID_Buku`)
    REFERENCES `db_perpustakaan`.`Buku` (`ID_Buku`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
