/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

/**
 *
 * @author Wendell
 */
public class menuDashboard extends javax.swing.JPanel {

    /**
     * Creates new form menuDashboard
     */
    public menuDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cardANGGOTA = new javax.swing.JPanel();
        anggota = new javax.swing.JLabel();
        jumlah_anggota = new javax.swing.JLabel();
        cardBUKU = new javax.swing.JPanel();
        BUKU = new javax.swing.JLabel();
        jumlah_buku = new javax.swing.JLabel();
        cardPEMINJAMAN = new javax.swing.JPanel();
        peminjaman = new javax.swing.JLabel();
        jumlah_peminjaman = new javax.swing.JLabel();
        cardPENGEMBALIAN = new javax.swing.JPanel();
        pengembalian = new javax.swing.JLabel();
        jumlah_pengembalian = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(690, 448));
        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        cardANGGOTA.setBackground(new java.awt.Color(0, 255, 204));

        anggota.setBackground(new java.awt.Color(204, 204, 204));
        anggota.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        anggota.setForeground(new java.awt.Color(102, 102, 102));
        anggota.setText("ANGGOTA");

        jumlah_anggota.setBackground(new java.awt.Color(51, 51, 51));
        jumlah_anggota.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jumlah_anggota.setForeground(new java.awt.Color(51, 51, 51));
        jumlah_anggota.setText("10");

        javax.swing.GroupLayout cardANGGOTALayout = new javax.swing.GroupLayout(cardANGGOTA);
        cardANGGOTA.setLayout(cardANGGOTALayout);
        cardANGGOTALayout.setHorizontalGroup(
            cardANGGOTALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardANGGOTALayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cardANGGOTALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(anggota)
                    .addComponent(jumlah_anggota))
                .addGap(39, 39, 39))
        );
        cardANGGOTALayout.setVerticalGroup(
            cardANGGOTALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardANGGOTALayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(anggota)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jumlah_anggota)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cardBUKU.setBackground(new java.awt.Color(0, 255, 204));

        BUKU.setBackground(new java.awt.Color(204, 204, 204));
        BUKU.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BUKU.setForeground(new java.awt.Color(102, 102, 102));
        BUKU.setText("BUKU");

        jumlah_buku.setBackground(new java.awt.Color(51, 51, 51));
        jumlah_buku.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jumlah_buku.setForeground(new java.awt.Color(51, 51, 51));
        jumlah_buku.setText("10");

        javax.swing.GroupLayout cardBUKULayout = new javax.swing.GroupLayout(cardBUKU);
        cardBUKU.setLayout(cardBUKULayout);
        cardBUKULayout.setHorizontalGroup(
            cardBUKULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardBUKULayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cardBUKULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BUKU)
                    .addComponent(jumlah_buku))
                .addGap(64, 64, 64))
        );
        cardBUKULayout.setVerticalGroup(
            cardBUKULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardBUKULayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BUKU)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jumlah_buku)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cardPEMINJAMAN.setBackground(new java.awt.Color(0, 255, 204));

        peminjaman.setBackground(new java.awt.Color(204, 204, 204));
        peminjaman.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        peminjaman.setForeground(new java.awt.Color(102, 102, 102));
        peminjaman.setText("PEMINJAMAN");

        jumlah_peminjaman.setBackground(new java.awt.Color(51, 51, 51));
        jumlah_peminjaman.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jumlah_peminjaman.setForeground(new java.awt.Color(51, 51, 51));
        jumlah_peminjaman.setText("10");

        javax.swing.GroupLayout cardPEMINJAMANLayout = new javax.swing.GroupLayout(cardPEMINJAMAN);
        cardPEMINJAMAN.setLayout(cardPEMINJAMANLayout);
        cardPEMINJAMANLayout.setHorizontalGroup(
            cardPEMINJAMANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardPEMINJAMANLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cardPEMINJAMANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(peminjaman)
                    .addComponent(jumlah_peminjaman))
                .addGap(20, 20, 20))
        );
        cardPEMINJAMANLayout.setVerticalGroup(
            cardPEMINJAMANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardPEMINJAMANLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(peminjaman)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jumlah_peminjaman)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cardPENGEMBALIAN.setBackground(new java.awt.Color(0, 255, 204));

        pengembalian.setBackground(new java.awt.Color(204, 204, 204));
        pengembalian.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        pengembalian.setForeground(new java.awt.Color(102, 102, 102));
        pengembalian.setText("PENGEMBALIAN");

        jumlah_pengembalian.setBackground(new java.awt.Color(51, 51, 51));
        jumlah_pengembalian.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jumlah_pengembalian.setForeground(new java.awt.Color(51, 51, 51));
        jumlah_pengembalian.setText("10");

        javax.swing.GroupLayout cardPENGEMBALIANLayout = new javax.swing.GroupLayout(cardPENGEMBALIAN);
        cardPENGEMBALIAN.setLayout(cardPENGEMBALIANLayout);
        cardPENGEMBALIANLayout.setHorizontalGroup(
            cardPENGEMBALIANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardPENGEMBALIANLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cardPENGEMBALIANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pengembalian)
                    .addComponent(jumlah_pengembalian))
                .addGap(20, 20, 20))
        );
        cardPENGEMBALIANLayout.setVerticalGroup(
            cardPENGEMBALIANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardPENGEMBALIANLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pengembalian)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jumlah_pengembalian)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Riwayat Peminjaman Buku");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cardANGGOTA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(cardBUKU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(cardPEMINJAMAN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(cardPENGEMBALIAN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 101, Short.MAX_VALUE)))
                        .addGap(20, 20, 20))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cardPENGEMBALIAN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardPEMINJAMAN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardBUKU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardANGGOTA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BUKU;
    private javax.swing.JLabel anggota;
    private javax.swing.JPanel cardANGGOTA;
    private javax.swing.JPanel cardBUKU;
    private javax.swing.JPanel cardPEMINJAMAN;
    private javax.swing.JPanel cardPENGEMBALIAN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel jumlah_anggota;
    private javax.swing.JLabel jumlah_buku;
    private javax.swing.JLabel jumlah_peminjaman;
    private javax.swing.JLabel jumlah_pengembalian;
    private javax.swing.JLabel peminjaman;
    private javax.swing.JLabel pengembalian;
    // End of variables declaration//GEN-END:variables
}
